### ISSUE TITLE
Suggestion: change bacnground color

### ISSUE THREAD

**Issue by samu22cr** [samu22cr/my-first-repository#1]
background color would look better if it was blue 

chanfes would look like this in the code:

```css
body {
	background-color: rgb(77, 88, 245);
}
```
